repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: ruff-format
        name: ruff-format
        entry: ruff format .
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        types: [python]
        pass_filenames: false
        always_run: true
